filter:
    excluded_paths: [framework/*, locale/*, docs/*, fonts/*, third_party/*, application/third_party/*, images/*, styles/*, styles-public/*, templates/*, themes/*, tmp/*, upload/*]
    paths: [application/*]
tools:
    php_code_sniffer:
        config:
            standard: "PSR1"
    php_pdepend:
        command: pdepend
    php_cs_fixer:
        config: { level: psr1 }